version: '3.8'
services:
  app:
    build: .
    image: 4natole/tp-node:1.0
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - tp_node_network
    volumes:
      - /usr/src/app/node_modules

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - tp_node_network
    volumes:
      - postgresql:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "1234:80"
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgresql:
  pgadmin:

networks:
  tp_node_network: