apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_USERNAME: c2E=
  REFRESH_TOKEN_SECRET: and0X3NlY3JldF9yZWZyZXNo
  ACCESS_TOKEN_SECRET: and0X3NlY3JldA==